version: 2

sources:
    - name: ecommerce
      database: ecommerce
      schema: ecommerce

      tables:
        - name: orders
        - name: order_items
        - name: customers
        - name: sellers
        - name: products



