
services:

  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    volumes:
      - ./source_data:/var/lib/postgresql/data:rw
    ports:
      - 5434:5434
    networks:
      - airflow

  # pg-admin:
  #   image: dpage/pgadmin4
  #   container_name: pg-admin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 1111:80
    # networks:
    #   - airflow

networks:
  airflow:
    external:
      name: airflow_default
